config/routes.rb
Rails.application.routes.draw do
  resources :recents, only: [:show, :index, :create, :destroy]
  root 'recents#index'

end

app/models/recent.rb
require './lib/assets/handlebars.rb'
require 'digest/md5'

class Recent < ActiveRecord::Base
  before_save :hash_url, :get_handles
  serialize :handles
  validates_presence_of :url_string, message: "can't be empty!"
  validates_format_of :url_string, with: URI::regexp(%w[http https]),
                      message: "needs to start with http:// or https://"

  protected
    def hash_url
      self.url_hash = Digest::MD5.hexdigest(url_string)
    end

    # find row by url_hash
    def self.check_by_hash(url)
      Recent.find_by(url_hash: Digest::MD5.hexdigest(url))
    end

    # fetch the url, parse the url, and store the result hash
    def get_handles
      self.handles = validate_handles(parse_relevent_handles(fetch_url_as_string(self.url_string).first))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recents_controller.rb
class RecentsController < ApplicationController
  before_action :set_recent, only: [:show, :destroy]

  def index
    @recent = Recent.new
    @recents = Recent.all
  end

  def show
    check_timestamp()
    @profile_cards = @recent.handles[:good]
    @bad_handles = @recent.handles[:bad]
  end

  def create
    @recent = Recent.new(recent_params)
    @existing = Recent.check_by_hash(@recent.url_string)
    
    if @existing 
      redirect_to @existing, notice: 'Url was successfully parsed before.'
    elsif @recent.save
      redirect_to @recent, notice: 'Url was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @recent.destroy
    redirect_to recents_url, notice: 'Url was successfully destroyed.'
  end

  private
    def set_recent
      @recent = Recent.find(params[:id])
    end

    # whitelist parameters
    def recent_params
      params.require(:recent).permit(:url_string)
    end

    # update it if it's more than 5 mins ago
    def check_timestamp
      @recent.save! if Time.now - @recent.updated_at >= 600
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recents_helper.rb
module RecentsHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p>A web application built for parsing twitter handles.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div>
      <%= link_to "Handlebars", root_path %>
    </div>
  </nav>
</header>
<div id="flash-div">
  <%= content_tag(:p, notice, class: 'notice') if notice.present? %>
  <%= content_tag(:p, alert, class: 'alert') if alert.present? %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Handlebars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body id="main-body">
  <span id='loading'><span>Loading Please Wait !</span></span>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/recents/_form.html.erb
<%= form_for(@recent) do |f| %>
  <% if @recent.errors.any? %>
    <div id="error-explanation">
      <h2>The form has <%= pluralize(@recent.errors.count, "error") %>:</h2>
      <ul>
        <% @recent.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_string %>
    <%= f.text_field :url_string, placeholder: "http:// or https:// . . ." %>
  </div>
  
  <div class="form-options">
    <%= f.submit "Find Twitter Handles"%>
  </div>
<% end %>

app/views/recents/_profile_card.html.erb
<% @profile_cards.each_with_index do |profile_card, index| %>
  <%= content_tag :div, class: "profile_card", id:"profile_card_#{index+1}" do %>
    <h3>
      <%= link_to profile_card.last[:profile_name], "https://twitter.com/#{profile_card.last[:handle].to_s}" %>
      <span><strong><%= "@" + profile_card.last[:handle] %></strong></span><%= %>
    </h3>
    <% [:location, :joined, :url, :tweets, :following, :followers, :likes].each do |e| %>
      <% if profile_card.last.include?(e) && e != :url && !profile_card.last[e].include?('recents/') %>
        <p><span><strong><%= e.to_s.capitalize %>:</strong> <%= profile_card.last[e] %></span></p>
      <% elsif profile_card.last.include?(e) && e == :url && !profile_card.last[e].include?('recents/') %>
        <p><span><strong>URL:</strong>
           <%= link_to profile_card.last[e], profile_card.last[e] %></span>
        </p>
      <% end %>
    <% end %>

    <div>
      <p><span><strong>Most Recent Tweet:</strong></span></p>
      <p class="tweet_title"><%= profile_card.last[:tweet_title] %></p>
      <p class="tweet_text"><%= profile_card.last[:tweet_text] %></p>
    </div>

  <% end %>
<% end %>

app/views/recents/_recent.html.erb
<% unless recent.handles[:good].blank? %>
  <%= div_for recent do %>
    <h3>
      <%= link_to recent.url_string, recent_path(recent) %>
      <span class="right" id='contact-options'>
        <span id="last-checked">Last Checked: <%= time_ago_in_words(recent.updated_at) %> ago</span> |
        <%= link_to 'Delete', recent_path(recent), data: { confirm: 'Are you sure?' },
                    method: :delete %>
      </span>
    </h3>
    <p><span><strong>Good Handles:</strong> <%= recent.handles[:good].keys.map{|x| "@"+x.to_s} %></span> <span><strong>Count:</strong> <%= recent.handles[:good].keys.size %></span></p>
  <% end %>
<% end %>

app/views/recents/index.html.erb
<h1>Welcome To Handlebars</h1>

<%= render 'form' %>

<div id="recent">
  <%= render @recents %>
</div>

app/views/recents/new.html.erb
<h1>Welcome To Handlebars</h1>

<%= render 'form' %>

<%= link_to 'Back', recents_path %>

app/views/recents/show.html.erb
<h1>Showing parsed results for <%= @recent.url_string %><span id="last-checked" class='right'>Last Checked: <%= time_ago_in_words(@recent.updated_at) %> ago</span></h1>

<p>The following are bad twitter handles that were found: <%= @bad_handles unless @bad_handles.nil? %></p>

<div id="recent">
  <%= render 'profile_card' unless @profile_cards.nil? %>
</div>

<div id="index-link">
  <%= link_to 'Back', recents_path %>
</div>